#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : resourceproto
Version  : 1.2.0
Release  : 4
URL      : http://xorg.freedesktop.org/releases/individual/proto/resourceproto-1.2.0.tar.bz2
Source0  : http://xorg.freedesktop.org/releases/individual/proto/resourceproto-1.2.0.tar.bz2
Summary  : Resource extension headers
Group    : Development/Tools
License  : MIT
Requires: resourceproto-doc

%description
X Resource Extension
This extension defines a protocol that allows a client to query the  X  server
about its usage of various resources.

%package dev
Summary: dev components for the resourceproto package.
Group: Development

%description dev
dev components for the resourceproto package.


%package doc
Summary: doc components for the resourceproto package.
Group: Documentation

%description doc
doc components for the resourceproto package.


%prep
%setup -q -n resourceproto-1.2.0

%build
%configure --disable-static
make V=1 %{?_smp_mflags}

%check
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/X11/extensions/XResproto.h
/usr/lib64/pkgconfig/*.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/doc/resourceproto/*
